version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www
    working_dir: /var/www
    networks:
      - my-laravel-network
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: mysjiu_jitsu_master
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: jitsu
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3305:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-laravel-network

networks:
  my-laravel-network:
    driver: bridge
volumes:
  mysql-data:
